sonar.projectKey=sasha-kas_refactoring-project2
sonar.organization=sasha-kas

sonar.projectName=Event Planning Board
sonar.projectVersion=1.0

sonar.sources=src
sonar.tests=tests
sonar.language=py
sonar.python.version=3.12

sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=junit.xml

sonar.qualitygate.wait=true
sonar.coverage.exclusions=**/tests/**,**/__init__.py